import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser, SignIn } from "@clerk/nextjs";
// I'm lost
const Home: NextPage = () => {

  const user = useUser();

  const {data, isLoading} = api.posts.getAll.useQuery();

  if (!data || isLoading) return <div>Loading...</div>

  //console.log(hello.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="bg-red-200 h-full w-full border-slate-400 md:max-w-2xl border-x">
          <div className="border-b border-slate-400 p-4 flex justify-center">
            <div className="flex justify-center">
              {!user.isSignedIn && <SignInButton />}
            </div>  
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (<div className="p-8 border-b border-slate-400" key={post.id}>{post.content}</div>))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
