import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { useUser} from "@clerk/nextjs";

const SinglePostPage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex justify-center h-screen">
        <div>Post View</div>
      </main>
    </>
  );
};

export default SinglePostPage;
